// Regenerates supabase/seed.sql from the app's catalog (app/data/markets.ts).
// markets.ts is the shape reference; the DB is the runtime source after this.
//
// Run from the supabase/ dir:  node scripts/gen-seed.mjs > seed.sql
// Country -> currency/locale mapping keeps the catalog market-aware (no hard-coded
// USD/US in the schema). v1 launches US-only; the mapping covers every country in
// the catalog so adding a live international market is a data change only.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const marketsTs = resolve(here, '../../lmc-app/app/data/markets.ts');
const src = readFileSync(marketsTs, 'utf8');

// Pull the three exported arrays out of the TS module without importing TS:
// grab the array literal text, strip TS type annotations, eval as JS.
function extractArray(name) {
  const re = new RegExp(`export const ${name}[^=]*=\\s*(\\[[\\s\\S]*?\\n\\];)`, 'm');
  const m = src.match(re);
  if (!m) throw new Error(`could not find ${name} in markets.ts`);
  // eslint-disable-next-line no-eval
  return eval(m[1].replace(/;\s*$/, ''));
}

const COUNTRIES = extractArray('COUNTRIES');
const MARKETS = extractArray('MARKETS');
const VENUES = extractArray('VENUES');

// Country -> { currency (ISO 4217), locale (BCP-47) }.
const COUNTRY_MONEY = {
  US: { currency: 'USD', locale: 'en-US' },
  GB: { currency: 'GBP', locale: 'en-GB' },
  CA: { currency: 'CAD', locale: 'en-CA' },
  AE: { currency: 'AED', locale: 'ar-AE' },
  SG: { currency: 'SGD', locale: 'en-SG' },
  ID: { currency: 'IDR', locale: 'id-ID' },
  AU: { currency: 'AUD', locale: 'en-AU' },
  MX: { currency: 'MXN', locale: 'es-MX' },
};
const moneyFor = (cc) => COUNTRY_MONEY[cc] ?? { currency: 'USD', locale: 'en-US' };

const q = (s) => (s == null ? 'null' : `'${String(s).replace(/'/g, "''")}'`);
const pt = (coord) =>
  Array.isArray(coord)
    ? `ST_SetSRID(ST_MakePoint(${coord[0]}, ${coord[1]}), 4326)`
    : 'null';

const lines = [];
lines.push('-- seed.sql — GENERATED by scripts/gen-seed.mjs from app/data/markets.ts.');
lines.push('-- Do not hand-edit; re-run the generator. Idempotent via on conflict.');
lines.push('');
lines.push('-- Markets ------------------------------------------------------------------');
for (const m of MARKETS) {
  const { currency, locale } = moneyFor(m.countryCode);
  const isLive = m.status === 'live';
  lines.push(
    `insert into public.markets (id, name, country, currency, locale, is_live, center) values (` +
      `${q(m.id)}, ${q(m.name)}, ${q(m.countryCode)}, ${q(currency)}, ${q(locale)}, ${isLive}, ${pt(m.center)})` +
      ` on conflict (id) do update set name = excluded.name, country = excluded.country, ` +
      `currency = excluded.currency, locale = excluded.locale, is_live = excluded.is_live, center = excluded.center;`,
  );
}
lines.push('');
lines.push('-- Venues -------------------------------------------------------------------');
// Stable venue id = market + slugified name (unique within the catalog).
const slug = (s) =>
  s
    .toLowerCase()
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
const seenIds = new Set();
for (const v of VENUES) {
  let id = `${v.marketId}-${slug(v.name)}`;
  while (seenIds.has(id)) id += '-x';
  seenIds.add(id);
  const isPartner = Boolean(v.partner);
  lines.push(
    `insert into public.venues (id, market_id, name, category, coord, is_partner) values (` +
      `${q(id)}, ${q(v.marketId)}, ${q(v.name)}, ${q(v.category)}, ${pt(v.coord)}, ${isPartner})` +
      ` on conflict (id) do update set market_id = excluded.market_id, name = excluded.name, ` +
      `category = excluded.category, coord = excluded.coord, is_partner = excluded.is_partner;`,
  );
}
lines.push('');

const out = lines.join('\n');
const target = resolve(here, '../seed.sql');
writeFileSync(target, out + '\n');
process.stderr.write(
  `seed.sql written: ${MARKETS.length} markets, ${VENUES.length} venues (${COUNTRIES.length} countries known)\n`,
);
