// Main filming screen styles — extracted from filming.tsx to keep that screen
// under 500 lines (CLAUDE.md). Imported back as `styles`.
//
// SPECIAL CASE: this screen has a live camera viewfinder. The viewfinder stays
// dark (it IS the camera feed). Only the HUD/info panels around the camera use
// the light token system.

import { StyleSheet } from 'react-native';
import { colors } from '../lib/theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  safe: { flex: 1 },
  scroll: { paddingHorizontal: 22, paddingBottom: 40, alignItems: 'center' },

  topBar: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 8,
    paddingBottom: 14,
  },
  backText: {
    fontFamily: 'Inter_500Medium',
    color: colors.red,
    fontSize: 14,
    letterSpacing: 0.5,
  },
  wireframeBadge: {
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 4,
    backgroundColor: 'rgba(255,107,0,0.12)',
  },
  wireframeBadgeText: {
    fontFamily: 'Inter_700Bold',
    color: '#FF6B00',
    fontSize: 9,
    letterSpacing: 1.4,
  },

  acceptedRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 14,
  },
  acceptedPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(22,163,74,0.10)',
    borderWidth: 1,
    borderColor: 'rgba(22,163,74,0.35)',
  },
  acceptedText: {
    fontFamily: 'Inter_700Bold',
    color: colors.verified,
    fontSize: 10,
    letterSpacing: 1.6,
  },
  priorityPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: colors.red,
    borderWidth: 1,
    borderColor: colors.red,
  },
  priorityPillText: {
    fontFamily: 'Inter_700Bold',
    fontSize: 9,
    color: colors.onRed,
    letterSpacing: 1.4,
  },

  venueName: {
    width: '100%',
    fontFamily: 'Inter_700Bold',
    fontSize: 26,
    color: colors.textPrimary,
    letterSpacing: 0.2,
    marginBottom: 4,
  },
  venueMetaRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: 16,
  },
  venueAddress: {
    fontFamily: 'Inter_500Medium',
    fontSize: 12.5,
    color: colors.textSecondary,
    letterSpacing: 0.2,
  },

  troubleBase: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 18,
  },
  troubleClosed: {
    backgroundColor: colors.surface,
    borderColor: colors.red,
  },
  troubleReported: {
    backgroundColor: 'rgba(22,163,74,0.06)',
    borderColor: 'rgba(22,163,74,0.35)',
    alignItems: 'center',
  },
  troubleExpanded: {
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 0,
    backgroundColor: colors.surface,
    borderColor: colors.red,
    paddingTop: 12,
    paddingBottom: 4,
  },
  troubleHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  troubleHeaderLabel: {
    fontFamily: 'Inter_700Bold',
    fontSize: 11,
    color: colors.red,
    letterSpacing: 1.4,
  },
  troubleTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: 12,
    color: colors.textPrimary,
    letterSpacing: 1.2,
    marginBottom: 3,
  },
  troubleSub: {
    fontFamily: 'Inter_400Regular',
    fontSize: 11.5,
    color: colors.textSecondary,
    letterSpacing: 0.2,
    lineHeight: 16,
  },
  troubleReasonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 11,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  troubleReasonText: {
    flex: 1,
    fontFamily: 'Inter_500Medium',
    fontSize: 13,
    color: colors.textPrimary,
    letterSpacing: 0.2,
  },

  // Countdown card — light surface with red accent on sub-label
  countdownCard: {
    width: '100%',
    backgroundColor: colors.red,
    overflow: 'hidden', // clip the CtaGlow gradient to the rounded corners
    borderRadius: 16,
    paddingVertical: 18,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.red,
    marginBottom: 22,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  countdownLabel: {
    fontFamily: 'Inter_700Bold',
    fontSize: 10,
    color: 'rgba(255,255,255,0.7)',
    letterSpacing: 2.5,
    marginBottom: 8,
  },
  countdown: {
    fontFamily: 'JetBrainsMono_700Bold',
    fontSize: 48,
    color: colors.white,
    letterSpacing: 3,
    marginBottom: 4,
  },
  countdownSub: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 11,
    color: 'rgba(255,255,255,0.85)',
    letterSpacing: 1.2,
  },

  stepsCard: {
    width: '100%',
    paddingLeft: 4,
    marginBottom: 18,
  },
  stepRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  stepLeft: { alignItems: 'center', width: 28, marginRight: 12 },
  stepDot: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.surface,
    borderWidth: 1.5,
    borderColor: colors.border,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepDotDone: {
    backgroundColor: colors.verified,
    borderColor: colors.verified,
  },
  stepDotActive: {
    backgroundColor: 'rgba(22,163,74,0.12)',
    borderColor: colors.verified,
  },
  stepDotPulse: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: colors.verified,
  },
  stepLine: {
    width: 1.5,
    height: 24,
    backgroundColor: colors.border,
    marginTop: 2,
  },
  stepLineDone: { backgroundColor: colors.verified },
  stepLabel: {
    flex: 1,
    fontFamily: 'Inter_500Medium',
    fontSize: 13,
    color: colors.textTertiary,
    paddingTop: 2,
    paddingBottom: 18,
    letterSpacing: 0.2,
  },
  stepLabelDone: { color: colors.textSecondary },
  stepLabelActive: {
    color: colors.textPrimary,
    fontFamily: 'Inter_700Bold',
  },

  gpsPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(22,163,74,0.08)',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: 'rgba(22,163,74,0.3)',
  },
  gpsText: {
    fontFamily: 'Inter_700Bold',
    color: colors.verified,
    fontSize: 10.5,
    letterSpacing: 0.6,
  },

  // Record button — stays on light background; the red circle is the visual anchor
  recordWrap: { alignItems: 'center', width: '100%', marginBottom: 14 },
  recordBtn: { alignItems: 'center', marginBottom: 12, padding: 8 },
  recordHalo: {
    position: 'absolute',
    width: 84,
    height: 84,
    borderRadius: 42,
    borderWidth: 1,
    borderColor: 'rgba(218,37,29,0.22)',
  },
  recordOuter: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 1,
    borderColor: 'rgba(218,37,29,0.45)',
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  recordOuterActive: {
    borderColor: colors.red,
  },
  recordInner: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  recordInnerActive: {},
  recordCircle: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: colors.red,
  },
  stopSquare: {
    width: 22,
    height: 22,
    borderRadius: 5,
    backgroundColor: colors.red,
  },
  recordHint: {
    fontFamily: 'Inter_500Medium',
    fontSize: 12.5,
    color: colors.textSecondary,
    letterSpacing: 0.3,
  },

  decisionCard: {
    width: '100%',
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 14,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  decisionTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  decisionTakeLabel: {
    fontFamily: 'Inter_700Bold',
    fontSize: 10,
    color: colors.verified,
    letterSpacing: 2,
  },
  takesRemaining: {
    fontFamily: 'Inter_500Medium',
    fontSize: 11,
    color: colors.textSecondary,
    letterSpacing: 0.2,
  },
  lastTakeBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: colors.amber,
    borderWidth: 1,
    borderColor: '#C99A1F',
  },
  lastTakeBadgeText: {
    fontFamily: 'Inter_700Bold',
    fontSize: 9,
    color: colors.black,
    letterSpacing: 1.4,
  },
  decisionTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: 17,
    color: colors.textPrimary,
    letterSpacing: 0.2,
    marginBottom: 4,
  },
  decisionSub: {
    fontFamily: 'Inter_400Regular',
    fontSize: 12.5,
    color: colors.textSecondary,
    lineHeight: 18,
    marginBottom: 14,
  },
  decisionButtonRow: {
    flexDirection: 'row',
    gap: 10,
  },
  retakeBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingVertical: 14,
  },
  retakeBtnText: {
    fontFamily: 'Inter_700Bold',
    color: colors.textPrimary,
    fontSize: 12,
    letterSpacing: 1.8,
  },
  submitBtn: {
    flex: 1.5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: colors.red,
    borderRadius: 12,
    paddingVertical: 14,
  },
  submitBtnFull: { flex: 1 },
  submitBtnText: {
    fontFamily: 'Inter_700Bold',
    color: colors.onRed,
    fontSize: 12,
    letterSpacing: 1.8,
  },
  uploadWrap: {
    width: '100%',
    backgroundColor: colors.surface,
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 14,
  },
  uploadHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  uploadStageLabel: {
    fontFamily: 'Inter_700Bold',
    fontSize: 11,
    color: colors.verified,
    letterSpacing: 2,
  },
  uploadPct: {
    fontFamily: 'JetBrainsMono_700Bold',
    fontSize: 18,
    color: colors.textPrimary,
    letterSpacing: 0.5,
  },
  uploadTrack: {
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.border,
    overflow: 'hidden',
    marginBottom: 10,
  },
  uploadFill: {
    height: '100%',
    backgroundColor: colors.verified,
    borderRadius: 3,
  },
  uploadSub: {
    fontFamily: 'Inter_400Regular',
    fontSize: 12,
    color: colors.textSecondary,
    lineHeight: 17,
    letterSpacing: 0.2,
  },

  earnNote: {
    fontFamily: 'Inter_700Bold',
    fontSize: 12,
    color: colors.verified,
    letterSpacing: 0.6,
    marginTop: 10,
  },
});
